name = "watykanczyk"
author = "hojraczek"
version = "1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61981642ce0cda0fd351edc281ab70a5c3aa42f253af22da5bbebf1d5cc43e14"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
