name = "watykanczyk"
author = "hojraczek"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e301a4fd46d2fd8cdceda043c9d4157c05871463452427a07684ba7159123e0"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
